package main

var worksSampleData = []Work{
	{
		ID:           "1",
		Title:        "La noche estrellada",
		Artist:       Artist{Name: "Vincent van Gogh", Biography: "Pintor neerlandés postimpresionista."},
		ImageURL:     "https://example.com/noche-estrellada.jpg",
		CreationYear: 1889,
		Technique:    "Óleo",
		Dimensions:   "73 x 92 cm",
		Era:          "Postimpresionismo",
		Description:  "Vista nocturna desde la ventana del sanatorio de Saint-Rémy.",
		Location:     "Sala 3",
		Availability: "EN_EXHIBICION",
		Comments: []Comment{
			{User: "ana", Text: "Increíble obra", Date: "2026-09-01"},
			{User: "luis", Text: "Los colores son hipnóticos", Date: "2026-09-05"},
		},
	},
	{
		ID:           "2",
		Title:        "Impresión, sol naciente",
		Artist:       Artist{Name: "Claude Monet", Biography: "Pintor francés, fundador del impresionismo."},
		ImageURL:     "https://example.com/impresion.jpg",
		CreationYear: 1872,
		Technique:    "Óleo",
		Dimensions:   "48 x 63 cm",
		Era:          "Impresionismo",
		Description:  "Puerto de Le Havre al amanecer.",
		Location:     "Ala Norte",
		Availability: "EN_EXHIBICION",
		Comments:     []Comment{},
	},
	{
		ID:           "3",
		Title:        "El pensador",
		Artist:       Artist{Name: "Auguste Rodin", Biography: "Escultor francés."},
		ImageURL:     "https://example.com/pensador.jpg",
		CreationYear: 1904,
		Technique:    "Escultura en bronce",
		Dimensions:   "186 x 98 x 140 cm",
		Era:          "Modernismo",
		Description:  "Figura masculina meditando, originalmente parte de La puerta del infierno.",
		Location:     "Depósito",
		Availability: "EN_DEPOSITO",
		Comments: []Comment{
			{User: "marta", Text: "Espero que la vuelvan a exhibir", Date: "2026-08-20"},
		},
	},
	{
		ID:           "4",
		Title:        "Abstracción en azul",
		Artist:       Artist{Name: "Lucía Ferrer", Biography: "Artista argentina contemporánea."},
		ImageURL:     "https://example.com/abstraccion.jpg",
		CreationYear: 2018,
		Technique:    "Acrílico",
		Dimensions:   "120 x 90 cm",
		Era:          "Contemporáneo",
		Description:  "Composición abstracta sobre lienzo, inspirada en el Río de la Plata.",
		Location:     "Sala 3",
		Availability: "EN_DEPOSITO",
		Comments:     []Comment{},
	},
}
